### ISSUE TITLE
php artisan Fatal error

### ISSUE THREAD

**Issue by delysh** [evolution-cms/evolution#1440]
Running `php artisan` command fails with fatal error:
`PHP Fatal error:  Uncaught Error: Class 'Dotenv\Environment\Adapter\EnvConstAdapter' not found in /vagrant/projects/evolution/core/vendor/illuminate/support/Env.php:67
Stack trace:
#0 /vagrant/projects/evolution/core/vendor/illuminate/support/Env.php(85): Illuminate\Support\Env::getFactory()
#1 /vagrant/projects/evolution/core/vendor/illuminate/support/Env.php(100): Illuminate\Support\Env::getVariables()
#2 /vagrant/projects/evolution/core/vendor/illuminate/support/helpers.php(265): Illuminate\Support\Env::get('HTTPS_PORT', '443')
#3 /vagrant/projects/evolution/core/includes/define.inc.php(5): env('HTTPS_PORT', '443')
#4 /vagrant/projects/evolution/core/bootstrap.php(23): require_once('/vagrant/projec...')
#5 /vagrant/projects/evolution/core/artisan(6): require('/vagrant/projec...')
#6 {main}
  thrown in /vagrant/projects/evolution/core/vendor/illuminate/support/Env.php on line 67`

After attempt to clear cache from the 'manager' nether 'manager' nor 'web' are accessible. Getting blank pages in both cases.     

Evolution version 2.0
PHP version 7.3

**Comment by delysh** [comment]
Update:
After new install everything was working. Then i ran command `php artisan package:create main` (I followed the video lesson 'Evolution CMS 2.0 Lessons: Packages'). This command updated number of composer repositories. One of these repos is 'vlucas/phpdotenv'.
`- Updating vlucas/phpdotenv (v3.6.0 => v4.1.4): Downloading (100%)`
At the end of the process the above mentioned error is thrown and everything stops working.

**Comment by delysh** [comment]
OK. I see that in Evolution 2.0.x this has been fixed. You can close this issue.
Maybe it's worth mentioning in the video lesson description that you need to install Evolution 2.0.x not (!) 2.0. ;-)
Keep up the good work!
