### ISSUE TITLE
[2.0.2] Cannot use Blade directives from custom service provider.

### ISSUE THREAD

**Issue by ZeeyN** [evolution-cms/evolution#1444]
If try to use it - Evo tells, yhat class Blade does not exists.
When hit
```
Blade::directive('test', function(){
            return 'test';
        });
```
error is
```
Fatal error:  Uncaught ReflectionException: Class blade.compiler does not exist in way_to_site/core/vendor/illuminate/container/Container.php:804
Stack trace:
#0 way_to_site/core/vendor/illuminate/container/Container.php(804): ReflectionClass->__construct('blade.compiler')
#1 way_to_site/core/vendor/illuminate/container/Container.php(682): Illuminate\Container\Container->build('blade.compiler')
#2 way_to_site/core/vendor/illuminate/container/Container.php(630): Illuminate\Container\Container->resolve('blade.compiler', Array)
#3 way_to_site/core/src/AbstractLaravel.php(464): Illuminate\Container\Container->make('blade.compiler', Array)
#4 way_to_site/core/custom/packages/sticker/src/StickerServiceProvider.php(40): EvolutionCMS\AbstractLaravel->make('bla in way_to_site/core/vendor/illuminate/container/Container.php on line 806
```

**Comment by Dmi3yy** [comment]
Need register like there: 

https://github.com/Dmi3yy/evocms-pwa/blob/master/example/core/custom/config/view/directive/evopwa.php.sample
